---
language: node_js
node_js:
- '8'
env:
  global:
  - secure: |-
      MHo0CEpSoHYkbrTLE4TBaYWUS48fLaPtgDjRhOuvSH/eWI+hpKmMKHZadrov
      fb0inn5Gw8uHzTAoaO3sbFP/APxiPKRi0QraznYlEwEgZRmpUULhFGA1bKq8
      EGq2KJiRko2drYAU5Amvmm89PUq6dmtAFjttJMQ7A7pVIuB+9TQ=
before_install:
  - gem install compass --no-ri --no-rdoc
  - npm install -g grunt-cli
before_script:
  - bower install
after_success: ./scripts/update-gh-pages.sh
